### ISSUE TITLE
Library uses lookbehind in regex

### ISSUE THREAD

**Issue by SimoTod** [nyariv/SandboxJS#4]
The library uses the lookbehind operator `?<=` which is currently not supported in firefox and safari.

https://github.com/nyariv/SandboxJS/blob/d327596c14b2bea861faa5579a956c899c0d90dc/src/Sandbox.ts#L1363

**Comment by nyariv** [comment]
Please close the issue if it is fixed

**Comment by SimoTod** [comment]
thanks
